config/routes.rb
Rails.application.routes.draw do
  resources :cats
end

app/models/cat.rb
class Cat < ActiveRecord::Base
  COLORS = %w(Red Blue Green Yellow)

  validates :birth_date, :color, :name, :sex, :description, presence: true
  validates :color, inclusion: { in: COLORS, message: "No other colors allowed!!!" }
  validates :sex, inclusion:{ in: %w(M F), message: "Sorry, no gender binaries."}
  has_many :cat_rental_requests, :dependent => :destroy

  def age
    require 'date'
    d = Date.new(2016, 8, 2)
    current_year = d.year
    cat_year = self.birth_date.year
    (current_year - cat_year)
  end

end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  validates :cat_id, :start_date, :end_date, :status, presence: true
  validates :status, inclusion: { in: %w(PENDING APPROVED DENIED), message: "Invalid status" }
  validate :overlapping_approved_requests
  belongs_to :cat

# Add a validation that no two APPROVED cat requests for the same cat can overlap in time.

  def overlapping_requests
    # start = self.start_date
    # ending = self.end_date
    # first_failure = self.cat.cat_rental_requests.where((self.start_date): start_date..end_date).to_a
    # second_failure = self.cat.cat_rental_requests.where((self.end_date): start_date..end_date).to_a
    # # third_failure = self.cat.cat_rental_requests.where('start_date: < start AND end_date: > ending').to_a
    # (first_failure + second_failure ).empty?
    CatRentalRequest
     .where.not(id: self.id)
     .where(cat_id: cat_id)
     .where(<<-SQL, start_date: start_date, end_date: end_date)
        NOT( (start_date > :end_date) OR (end_date < :start_date) )
     SQL
  end

  def overlapping_approved_requests
    unless overlapping_requests.where("status = 'APPROVED'").empty?
      errors[:bad_request] << "Invalid date range, dates overlap"
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
  end

  def show
    @cat = Cat.find_by_id(params[:id])
  end

  def new
    @cat = Cat.new
  end

  def create
    @cat = Cat.new(cat_params)
      if @cat.save
        redirect_to cat_url(@cat)
      else
        render @cat.errors.full_messages
      end
  end

  def edit
    @cat = Cat.find_by_id(params[:id])
  end

  def update
    @cat = Cat.find_by_id(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render @cat.errors.full_messages
    end
  end


  private

  def cat_params
    params.require(:cat).permit(:name, :sex, :color, :birth_date, :description)
  end





end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/edit.html.erb
<h1>Edit <%= @cat.name %></h1>

<%= render "./layouts/form" %>

app/views/cats/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <%= link_to("Make a new cat", new_cat_url) %>
        <% @cats.each do |kitty| %>
          <ul>
            <li>
              <ul>
                <li><%= link_to(kitty.name, cat_url(kitty)) %></li>
                <li><%= kitty.birth_date %></li>
                <li><%= kitty.color %></li>
                <li><%= kitty.sex %></li>
                <li><%= kitty.description %></li>
              </ul>
            </li>
          </ul>
        <% end %>
  </body>
</html>

app/views/cats/new.html.erb
<h1>Submit A Cat</h1>
<!-- <form action= "<%= cats_url %>" method="POST">
  <label for="Name">
    Name:
    <input type="text" name="cat[name]">
  </label>
  <label for="Sex">
    M
    <input type="radio" name="cat[sex]" value="M">
    F
    <input type="radio" name="cat[sex]" value="F">
  </label>
  <label for="Color">
    Color:
    <select name="cat[color]">
      <option value="">Option</options>
      <option value="Red">Red</options>
      <option value="Yellow">Yellow</options>
      <option value="Blue">Blue</options>
      <option value="Green">Green</options>
    </select>
  </label>
  <label for="date">Birth date:
    <input type='date' name='cat[birth_date]'>
  </label>
  <label>
    <textarea name="cat[description]" rows="8" cols="40">desribe your cat</textarea>
  </label>
  <input type="submit" value="Submit your cat">
</form> -->

<%= render "./layouts/form" %>

app/views/cats/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title><%= @cat.name %></title>
  </head>
  <body>
    <h1> <%= @cat.name %> </h1>
    <table>
      <tr>
        <th>Birth Date</th>
        <th>Sex</th>
        <th>Color</th>
        <th>Description</th>
      </tr>
      <tr>
        <td><%= @cat.birth_date %></td>
        <td><%= @cat.sex %></td>
        <td><%= @cat.color %></td>
        <td><%= @cat.description %></td>
      </tr>
    </table>
  </body>
</html>

app/views/layouts/_form.html.erb
<% action_url = @cat.persisted? ? cat_url(@cat) : cats_url %>
<% form_method = @cat.persisted? ? "PATCH" : "POST" %>
<% submit_text = @cat.persisted? ? "Update Cat!" : "Create Cat!" %>


<form action= "<%= action_url %>" method="POST">
  <input type="hidden" name="_method" value="<%= form_method %>">
  <label for="Name">
    Name:<input type="text" name="cat[name]" value=" <%= @cat.name %>">
  </label>
  <label for="Sex">
    M
    <input type="radio" name="cat[sex]" value="M" <%= @cat.sex == "M" ? "checked" : "false" %>>
    F
    <input type="radio" name="cat[sex]" value="F" <%= @cat.sex == "F" ? "checked" : "false" %>>
  </label>
  <label for="Color">
    Color:
    <select name="cat[color]">
      <option value="" >Option</options>
      <option value="Red"<%= @cat.color == "Red" ? "selected" : "false" %>>Red</options>
      <option value="Yellow" <%= @cat.color == "Yellow" ? "selected" : "false" %>>Yellow</options>
      <option value="Blue" <%= @cat.color == "Blue" ? "selected" : "false" %>>Blue</options>
      <option value="Green" <%= @cat.color == "Green" ? "selected" : "false" %>>Green</options>
    </select>
  </label>
  <label for="date">Birth date:
    <input type='date' name='cat[birth_date]' value="<%= @cat.birth_date.to_s %>">
  </label>
  <label>
    <textarea name="cat[description]" rows="8" cols="40"><%= @cat.description %></textarea>
  </label>
  <input type="submit" value="<%= submit_text %>">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NnCats</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
</head>

<body>

<%= yield %>

</body>
</html>